# Generated by Django 5.0.1 on 2024-01-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0002_dweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='body',
            field=models.CharField(max_length=250),
        ),
    ]
