# Generated by Django 5.0.1 on 2024-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0005_alter_comment_options_profile_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='images/Users/Profiles/default.png', upload_to=''),
        ),
    ]
