# Generated by Django 5.0.1 on 2024-08-11 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0009_alter_dweet_options_comment_commentimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Dweet'), ('C', 'Comment'), ('R', 'Reply'), ('', '')], default='', max_length=1)),
                ('reaction', models.CharField(choices=[('', ''), ('LO', 'Love'), ('LI', 'Like'), ('DI', 'Dislike'), ('HA', 'Hate')], default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='astro.reaction'),
        ),
        migrations.AddField(
            model_name='dweet',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='astro.reaction'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='astro.reaction'),
        ),
    ]
