# Generated by Django 5.0.1 on 2024-08-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0010_reaction_comment_reactions_dweet_reactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dweet',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reactions',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
